workflows:
  D-shorts APK:
    name: D-shorts APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        NODE_VERSION: 20
        EXPO_NO_DOTENV: 1
        ADMIN_EMAIL: unclediriisa@gmail.com
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npx expo install --fix
      - name: Prebuild Android
        script: |
          rm -rf android
          npx expo prebuild --platform android --clean
      - name: Build APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
